apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofmun-keycloak
  namespace : forms-flow-idm
  labels:
    app.kubernetes.io/name: sofmunkeycloak
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: sofmunkeycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sofmunkeycloak
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: sofmunkeycloak
          image: sofiamunicipalitydigitall/forms-flow-idm:latest
#          command: ["/opt/jboss/keycloak/bin/standalone.sh"]
#          args: ["-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/formsflow-ai-realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: KC_DB_USERNAME
              value: ""
            - name: KC_DB_PASSWORD
              value: ""
            - name: KC_DB_URL
              value: "jdbc:postgresql://172.23.230.134:5432/keycloakdbdev"
            - name: DB_PORT
              value: "5432"
            - name: KC_DB
              value: "postgres"
            - name: DB_DATABASE
              value: ""
            - name: KEYCLOAK_USER
              value: ""
            - name: KEYCLOAK_PASSWORD
              value: ""
            - name: KC_HOSTNAME
              value: "identity-dev-eservices.egov.bg"
            - name: KEYCLOAK_ADMIN
              value: ""
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: ""
            - name: KEYCLOAK_DEFAULT_THEME
              value: "formsflow"
            - name: ENTRYPOINT
              value: "/opt/keycloak/bin/kc.sh"
            - name: KEYCLOAK_WELCOME_THEME
              value: formsflow
            - name: sslRequired
              value: "NONE"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"  
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI
              value: "true"
            - name: KC_SPI_USER_CHECK_EVROTRUST_INTEGRATIONS_URL
              value: "http://forms-flow-eforms-integrations-svc.form-flow-eforms-integrations.svc.cluster.local:8002/integrations/evrotrust/user/check"
            - name: KC_FEATURES
              value: "declarative-user-profile,admin-fine-grained-authz"