apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofmun-keycloak
  namespace : forms-flow-idm
  labels:
    app.kubernetes.io/name: sofmunkeycloak
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sofmunkeycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sofmunkeycloak
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: sofmunkeycloak
          image: sofiamunicipalitydigitall/forms-flow-idm:latest
#          command: ["/opt/jboss/keycloak/bin/standalone.sh"]
#          args: ["-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/formsflow-ai-realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: firebase
              mountPath: /opt/keycloak/firebase
          env:
            - name: KC_DB_USERNAME
              value: "keycloak1"
            - name: KC_DB_PASSWORD
              value: "s2wBbrWPGf"
            - name: KC_DB_URL
              value: "jdbc:postgresql://172.23.230.134:5432/keycloakdbdev1"
            - name: DB_PORT
              value: "5432"
            - name: KC_DB
              value: "postgres"
            - name: DB_DATABASE
              value: "keycloakdbdev1"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: KC_HOSTNAME
              value: "identity-dev-eservices.egov.bg"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://identity-dev-eservices.egov.bg/auth"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KEYCLOAK_DEFAULT_THEME
              value: "formsflow"
            - name: ENTRYPOINT
              value: "/opt/keycloak/bin/kc.sh"
            - name: KEYCLOAK_WELCOME_THEME
              value: formsflow
            - name: sslRequired
              value: "NONE"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"  
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI
              value: "true"
            - name: KC_SPI_USER_CHECK_EVROTRUST_INTEGRATIONS_URL
              value: "http://forms-flow-eforms-integrations-svc.form-flow-eforms-integrations.svc.cluster.local:8002/integrations/evrotrust/user/check"
            - name: KC_FEATURES
              value: "declarative-user-profile,admin-fine-grained-authz"
            - name: KC_PROXY
              value: "edge"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_FRONTEND_URL
              value: "https://identity-dev-eservices.egov.bg/auth/"
            - name: KC_SPI_CODE_CHECK_CONFIRM_CODE_KEYCLOAK_HOME_URL
              value: "https://identity-dev-eservices.egov.bg/auth"
            - name: KC_SPI_CODE_CHECK_CONFIRM_CODE_CHECK_CONFIRM_STATUS_PATH
              value: "/realms/eServices/message/authentication-code/check-confirm-status"
            - name: KC_SPI_MESSAGE_SENDER_FIREBASE_SENDER_ACCOUNT_SETTINGS_FILE_PATH
              value: "/opt/keycloak/firebase/firebase-service-account.json"
            - name: KC_QUARKUS_PROPERTIES_ENABLED
              value: "true"
            - name: KC_SPI_MOBILE_LOGIN_MOBILE_LOGIN_LOGIN_EXPIRES_IN
              value: "900"
            - name: KC_SPI_MOBILE_LOGIN_MOBILE_LOGIN_MAX_LOGIN_COUNT
              value: "25"
      volumes:
        - name: firebase
          nfs:
            server: 172.23.230.140
            path: /pvc/keycloak/firebase