apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-flow-bpm
  namespace : forms-flow-bpm
  labels:
    app.kubernetes.io/name: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: camunda
  template:
    metadata:
      labels:
        app.kubernetes.io/name: camunda
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: form-flow-bpm
          image: sofiamunicipalitydigitall/forms-flow-bpm:latest
          ports:
            - containerPort: 8000
              name: http-camunda
              protocol: TCP
          env:
            - name: KEYCLOAK_URL_REALM
              value: "forms-flow-ai"
            - name: KEYCLOAK_URL
              value: "http://forms-flow-idm-svc.forms-flow-idm.svc.cluster.local:80"
            - name: KEYCLOAK_CLIENTID
              value: "forms-flow-bpm"
            - name: KEYCLOAK_CLIENTSECRET
              value: "e4bdbd25-1467-4f7f-b993-bc4b1944c943"
            - name: CAMUNDA_JDBC_URL
              value: "jdbc:postgresql://192.168.201.46:5432/camundadbdev"
            - name: CAMUNDA_JDBC_USER
              value: "camunda"
            - name: CAMUNDA_JDBC_PASSWORD
              value: "jw8s0F4"
            - name: CAMUNDA_JDBC_DRIVER
              value: "org.postgresql.Driver"
            - name: CAMUNDA_APP_ROOT_LOG_FLAG
              value: "error"
            - name: FORMSFLOW_API_URL
              value: "FORMSFLOW_API_URL"
            - name: FORMIO_URL
              value: "FORMIO_URL"
            - name: APP_SECURITY_ORIGIN
              value: "*"
            - name: WEBSOCKET_SECURITY_ORIGIN
              value: "http://localhost:3000"
            - name: WEBSOCKET_MESSAGE_TYPE
              value: "TASK_EVENT"
            - name: WEBSOCKET_ENCRYPT_KEY
              value: "giert989jkwrgb@DR55"
            - name: DATA_BUFFER_SIZE
              value: "2"
            - name: IDENTITY_PROVIDER_MAX_RESULT_SIZE
              value: "250"
            - name: KEYCLOAK_WEB_CLIENTID
              value: "forms-flow-web"
            - name: KEYCLOAK_ENABLE_CLIENT_AUTH
              value: "false"
            - name: BPM_CLIENT_CONN_TIMEOUT
              value: "5000"
            - name: DATA_ANALYSIS_URL
              value: "http://localhost:6000/analysis"
            - name: CUSTOM_SUBMISSION_URL
              value: "http://{your-ip-address}:{port}"
            - name: CUSTOM_SUBMISSION_ENABLED
              value: "false"
            - name: MULTI_TENANCY_ENABLED
              value: "false"
            - name: FORMSFLOW_ADMIN_URL
              value: "http://localhost:8000"
            - name: REDIS_ENABLED
              value: "false"
            - name: REDIS_HOST
              value: "{redis-hostname}"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSCODE
              value: "changeme"
            - name: SESSION_COOKIE_SECURE
              value: "false"