version: "3.7"

services:
  forms-flow-web:
    container_name: forms-flow-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - REACT_APP_API_SERVER_URL=${REACT_APP_API_SERVER_URL}
        - REACT_APP_API_PROJECT_URL=${REACT_APP_API_PROJECT_URL}
        - REACT_APP_KEYCLOAK_CLIENT=${REACT_APP_KEYCLOAK_CLIENT:-forms-flow-web}
        - REACT_APP_WEB_BASE_URL=${REACT_APP_WEB_BASE_URL}
        - REACT_APP_BPM_URL=${REACT_APP_BPM_URL}
        - REACT_APP_WEBSOCKET_ENCRYPT_KEY=${REACT_APP_WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
        - REACT_APP_KEYCLOAK_URL_REALM=${REACT_APP_KEYCLOAK_URL_REALM:-forms-flow-ai}
        - REACT_APP_KEYCLOAK_URL=${REACT_APP_KEYCLOAK_URL}
        - REACT_APP_APPLICATION_NAME=${REACT_APP_APPLICATION_NAME:-formsflow.ai}
        - REACT_APP_USER_ACCESS_PERMISSIONS=${REACT_APP_USER_ACCESS_PERMISSIONS}
        - REACT_APP_WEB_BASE_CUSTOM_URL=${REACT_APP_WEB_BASE_CUSTOM_URL}
        - REACT_APP_MULTI_TENANCY_ENABLED=${REACT_APP_MULTI_TENANCY_ENABLED:-false}
        - REACT_APP_TENANT_ID=${REACT_APP_TENANT_ID}
        - REACT_APP_MT_ADMIN_BASE_URL=${REACT_APP_MT_ADMIN_BASE_URL}
        - REACT_APP_MT_ADMIN_BASE_URL_VERSION=${REACT_APP_MT_ADMIN_BASE_URL_VERSION}
        - REACT_APP_CUSTOM_SUBMISSION_URL=${REACT_APP_CUSTOM_SUBMISSION_URL}
        - REACT_APP_CUSTOM_SUBMISSION_ENABLED=${REACT_APP_CUSTOM_SUBMISSION_ENABLED:-false}
        - REACT_APP_DRAFT_ENABLED=${REACT_APP_DRAFT_ENABLED:-false}
        - REACT_APP_DRAFT_POLLING_RATE=${REACT_APP_DRAFT_POLLING_RATE}
        - REACT_APP_DRAFT_FEEDBACK_ENABLED=${REACT_APP_DRAFT_FEEDBACK_ENABLED}
        - REACT_APP_DRAFT_SAVE_ON_EXIT_ENABLED=${REACT_APP_DRAFT_SAVE_ON_EXIT_ENABLED}
        - REACT_APP_DRAFT_CREATE_ON_INIT_ENABLED=${REACT_APP_DRAFT_CREATE_ON_INIT_ENABLED}
        - REACT_APP_CHECK_APPLICATION_PERMISSIONS_ENABLED=${REACT_APP_CHECK_APPLICATION_PERMISSIONS_ENABLED}
        - REACT_APP_FORM_ALERTS_ENABLED=${REACT_APP_FORM_ALERTS_ENABLED}
        - REACT_APP_MOBILE_SECTIONS_ENABLED=${REACT_APP_MOBILE_SECTIONS_ENABLED}
        - REACT_APP_DRAFT_DELETE_CTA_ENABLED=${REACT_APP_DRAFT_DELETE_CTA_ENABLED}
        - REACT_APP_TASK_LIST_DISABLE_FILTER=${REACT_APP_TASK_LIST_DISABLE_FILTER}
        - REACT_APP_TRANSLATE_BPMN_MODELER=${REACT_APP_TRANSLATE_BPMN_MODELER}
        - REACT_APP_TRANSLATE_FORM_BUILDER=${REACT_APP_TRANSLATE_FORM_BUILDER}
        - REACT_APP_MY_SERVICES_LOCAL_TAXES_ENABLED=${REACT_APP_MY_SERVICES_LOCAL_TAXES_ENABLED}
        - REACT_APP_SM_NEW_DESIGN_ENABLED=${REACT_APP_SM_NEW_DESIGN_ENABLED}
        - REACT_APP_CHECK_ASSURANCE_LEVEL_ENABLED=${REACT_APP_CHECK_ASSURANCE_LEVEL_ENABLED}
        - REACT_APP_EPAYMENT_REDIRECT_URL=${REACT_APP_EPAYMENT_REDIRECT_URL}
        - REACT_APP_EPAYMENT_ACCESS_CODE_LOGIN_URL=${REACT_APP_EPAYMENT_ACCESS_CODE_LOGIN_URL}
        - REACT_APP_CURRENT_ADDRESS_FORM_PATH=${REACT_APP_CURRENT_ADDRESS_FORM_PATH}
        - REACT_APP_PERMANENT_ADDRESS_FORM_PATH=${REACT_APP_PERMANENT_ADDRESS_FORM_PATH}
        - REACT_APP_FORM_PREFILLED_DATA_INPUT_NAME=${REACT_APP_FORM_PREFILLED_DATA_INPUT_NAME}
        - REACT_APP_EXPORT_PDF_ENABLED=${REACT_APP_EXPORT_PDF_ENABLED:-false}
        - REACT_APP_PUBLIC_WORKFLOW_ENABLED=${REACT_APP_PUBLIC_WORKFLOW_ENABLED:-false}
        - REACT_APP_DOCUMENT_SERVICE_URL=${REACT_APP_DOCUMENT_SERVICE_URL}
        - REACT_APP_OPENTELEMETRY_SERVICE=${REACT_APP_OPENTELEMETRY_SERVICE:-false}
        - REACT_APP_SHOW_AUTO_FULFILLMENT_CHECKBOX=${REACT_APP_SHOW_AUTO_FULFILLMENT_CHECKBOX}        
    ports:
      - "3000:8080"
    tty: true
