apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-flow-analytics
  namespace : forms-flow-analytics
  labels:
    app.kubernetes.io/name: analytics
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: form-flow-analytics
          image: formsflow/redash:10.1.4
          ports:
            - containerPort: 5000
              name: analytics
              protocol: TCP
          env:
            - name: REDASH_HOST
              value: "http://localhost:5000"
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: REDASH_LOG_LEVEL
              value: "INFO"
            - name: REDASH_REDIS_URL
              value: "redis://localhost:5000/0"
            - name: POSTGRES_USER
              value: "redis"
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_DB
              value: ""
            - name: REDASH_COOKIE_SECRET
              value: ""
            - name: REDASH_SECRET_KEY
              value: ""
            - name: REDASH_DATABASE_URL
              value: ""
            - name: REDASH_CORS_ACCESS_CONTROL_ALLOW_ORIGIN
              value: "*"
            - name: REDASH_REFERRER_POLICY
              value: "no-referrer-when-downgrade"
            - name: REDASH_CORS_ACCESS_CONTROL_ALLOW_HEADERS
              value: "Content-Type, Authorization"