apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-flow-forms
  namespace : forms-flow-forms
  labels:
    app.kubernetes.io/name: forms
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: forms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forms
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: form-flow-forms
          image: formsflow/forms-flow-forms:v5.1.0
         # lifecycle:
         #   postStart:
         #     exec:
         #       command: ["/bin/sh", "-c", "echo '140.82.121.4 github.com ' >> /etc/hosts && echo '140.82.121.9 codeload.github.com' >> /etc/hosts" ]
          stdin: true 
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true 
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /mnt/external-services/acstre/documents
              name: documents
          env:
            - name: DEBUG
              value: "*"
            - name: FORMIO_DB_USERNAME
              value: "formsio"
            - name: FORMIO_DB_PASSWORD
              value: "WhN3c5meUb"
            - name: FORMIO_DB_DATABASE
              value: "formsiodbdev"
            - name: ROOT_EMAIL
              value: "iiliev@digitall.com"
            - name: ROOT_PASSWORD
              value: "fd1cnUW2Rp608S2"
            - name: FORMIO_CLIENT_UI
              value: "true" 
            - name: FORMIO_DOMAIN
              value: "https://forms-dev-eservices.egov.bg"
            - name: FORMIO_JWT_SECRET
              value: "test-secret"
            - name: FORMIO_JWT_EXPIRE
              value: "240"
            - name: MULTI_TENANCY_ENABLED
              value: "true"
            - name: NODE_CONFIG
              value: "{\"mongo\":\"mongodb://formsio:WhN3c5meUb@172.23.230.134:27017/formsiodbdev\"}"
      volumes:
       - name: documents
         nfs:
           path: /pvc/documents
           server: 172.23.230.140