apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-flow-admin
  namespace : forms-flow-admin
  labels:
    app.kubernetes.io/name: formsflowadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: formsflowadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: formsflowadmin
    spec:
      imagePullSecrets:
        - name: private-registry
      containers:
        - name: formsflowadmin
          image: sofiamunicipalitydigitall/formsflow-admin-api:latest
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1001
         # command: [ "/bin/bash", "-c", "--" ]
         # args: [ "while true; do sleep 3600; done;" ]
          ports:
            - containerPort: 5000
              name: http-api
              protocol: TCP
          env:
            - name: DATABASE_USERNAME
              value: "adminapi"
            - name: DATABASE_PASSWORD
              value: "jw8s0F4"
            - name: DATABASE_NAME
              value: "adminapidbdev"
            - name: DATABASE_HOST
              value: "172.23.230.134"
            - name: DATABASE_PORT
              value: "5432"
            - name: FLASK_ENV
              value: "development"
            - name: JWT_OIDC_WELL_KNOWN_CONFIG
              value: "https://identity-dev-eservices.egov.bg/auth/realms/eServices/.well-known/openid-configuration"
            - name: JWT_OIDC_JWKS_URI
              value: "https://identity-dev-eservices.egov.bg/auth/realms/eServices/protocol/openid-connect/certs"
            - name: JWT_OIDC_ISSUER
              value: "https://identity-dev-eservices.egov.bg/auth/realms/eServices"
            - name: JWT_OIDC_AUDIENCE
              value: "forms-flow-web"
            - name: JWT_OIDC_CACHING_ENABLED
              value: "True"
            - name: JWT_OIDC_TEST_ALGORITHMS
              value: "RS256"
            - name: KEYCLOAK_URL
              value: "https://identity-dev-eservices.egov.bg"
            - name: KEYCLOAK_URL_REALM
              value: "eServices"
            - name: FORMSFLOW_WEB_URL
              value: "https://dev-eservices.sofia.bg"
            - name: FORMSFLOW_ADMIN_WEB_URL
              value: "https://dev-eservices.egov.bg"
            - name: BPM_API_URL
              value: "http://forms-flow-bpm-svc.forms-flow-bpm.svc.cluster.local:8080/camunda"
            - name: BPM_CLIENT_SECRET
              value: "SDi9yOoPH0wKncJw4fFlSkuZf6Ir5Lbc"
            - name: KEYCLOAK_ADMIN_CLIENT
              value: "forms-flow-bpm"
            - name: KEYCLOAK_ADMIN_SECRET
              value: "SDi9yOoPH0wKncJw4fFlSkuZf6Ir5Lbc"
            - name: INSIGHT_API_URL
              value: "http://forms-flow-analytics-svc.forms-flow-analytics.svc.cluster.local:5000"
            - name: INSIGHT_API_KEY
              value: "MxlZK65GyqWuVM3ncZBLHTgNrgKr777w0vHxMdcG"
            - name: FORMIO_ROOT_EMAIL
              value: "iiliev@digitall.com"
            - name: FORMIO_ROOT_PASSWORD
              value: "fd1cnUW2Rp608S2"
            - name: FORMIO_URL
              value: "http://forms-flow-forms-svc.forms-flow-forms.svc.cluster.local:3001"
            - name: FORMIO_JWT_SECRET
              value: "test-secret"